---
title: 'PFAS and environmental justice (beta version)'
author: "Jahred Liddie"
output:
  html_document:
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
# load data and set up libraries
library(leaflet)
library(sf)
library(maps)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)

# PFAS data
CWS.counties <- st_read("../../Merged PFAS data/CWS_formapping.geojson")
centroids <- st_read("../../Merged PFAS data/CWS_centroid.geojson")
ucmr.counties <- st_read("../../Merged PFAS data/UCMR_formapping.geojson")

CWS.counties <- st_transform(CWS.counties, crs = st_crs(centroids))
ucmr.counties <- st_transform(ucmr.counties, crs = st_crs(centroids))

# PFAS source data
  # MFTA
  military <- geojsonio::geojson_read("../../PFAS point source data/Military_2020MARCH04.geojson", what = "sp")
  military <- st_as_sf(military, )

  # airports
  airports <- readxl::read_excel("../../PFAS point source data/Part 139_cert_airports.xlsx")
  airports <- as.data.frame(airports)
  
  # epa stewardship sites
  epa <- readxl::read_excel("../../PFAS point source data/EPA 2010.2015 PFOA Stewardship Program sites.xlsx")
  
  # CWNS wastewater treatment plants
  WWTP <- read.csv("../../PFAS point source data/WWTP facility_details.csv")
  
  # sources for secondary analyses: landfills from LMOP
  landfills <- read.csv("../../PFAS point source data/Secondary analysis/landfills_ewg.csv")
  
  landfills.lmop <- read.csv("../../PFAS point source data/Secondary analysis/landfilllmopdata_clean.csv")

  CWS.states <- c("california", "colorado", "kentucky", "massachusetts", "michigan",
              "maryland", "new hampshire", "new jersey", "pennsylvania", "ohio",
              "vermont")
  
  ucmr.states <- c(tolower(ucmr.counties$state_name))
    
  # note: need to intersect military + airports with US boundary before mapping
  # also explore not showing points at first
  
  # county boundaries
  # CWS.counties <- map_data("county", regions = CWS.states)
  # ucmr.counties <- map_data("county", regions = ucmr.states)
  #   
  # CWS.counties <- st_as_sf(CWS.counties, coords = c("long", "lat"),
  #                          crs = st_crs(centroids))
  # ucmr.counties <- st_as_sf(ucmr.counties, coords = c("long", "lat"),
  #                           crs = st_crs(centroids))

knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE, results='hide', echo = FALSE}
# clean up source data
  # ignoring WWTPs for now because there aren't points available
  # # add leading zero to HUC codes if they are under 8 characters
  # WWTP$Watershed.HUC <- ifelse(str_length(WWTP$Watershed.HUC) < 8, 
  #                               paste("0", WWTP$Watershed.HUC, sep=""),
  #                               WWTP$Watershed.HUC)
  # 
  # WWTP.HUCs <- WWTP %>% group_by(Watershed.HUC, Watershed.Name) %>% 
  #   dplyr::summarise(WWTP_count = n(), 
  #          WWTP_existingtotalflow_Mgal.d = sum(as.numeric(Existing.Total.Flow..Mgal.d.))) %>% 
  #   ungroup()
  # 
  # WWTP.HUCs <- WWTP.HUCs %>% dplyr::rename(
  #   HUC_CODE = Watershed.HUC,
  #   HUC_NAME = Watershed.Name
  # ) 

  ### Military sites ###
  # note: 9 of those dropped from here are in AK
  # st_crs(military) == st_crs(centroids) # check if true
  # military$CWS.ind <- st_intersects(military, counties)
  
  ### EPA Stewardship sites ###
  # separate into lat and lon
  epa <- separate(epa, col = "Coordinates", into = c("lat", "lon"), sep = ",")
  
  # convert to sf object
  epa <- st_as_sf(epa, coords = c("lon", "lat"), crs = "NAD83")
  epa <- st_transform(epa, crs = st_crs(centroids))
  epa$CWS.ind <- epa$State_ABV %in% unique(CWS.counties$state)
  epa$ucmr.ind <- epa$State_ABV %in% unique(ucmr.counties$state)
  
  ### Airports ###
  # clean up data
  airports <- airports %>% dplyr::select(LocationID, Region, State, StateName, County, 
                                              CountyState, City, FacilityName, ARPLatitude, 
                                              ARPLatitudeS, ARPLongitude, ARPLongitudeS)
  
  airports <- separate(airports, col = "ARPLatitude", 
                       into = c("lat.deg", "lat.min", "lat.sec.dir"), sep = "-")
  
  airports <- separate(airports, col = "ARPLongitude", 
                       into = c("lon.deg", "lon.min", "lon.sec.dir"), sep = "-")
  
  # create columns without direction
  airports <- airports %>% 
    mutate(lat.sec = as.numeric(substr(lat.sec.dir, 1, nchar(lat.sec.dir)-1)),
           lon.sec = as.numeric(substr(lon.sec.dir, 1, nchar(lon.sec.dir)-1))) 
  
  # calculate lat and lon
  airports <- airports %>% 
    mutate(
      lat = ifelse(grepl("N", lat.sec.dir), 
                        as.numeric(lat.deg) + as.numeric(lat.min)/60 + lat.sec/3600,
                        -1 * (as.numeric(lat.deg) + as.numeric(lat.min)/60 + lat.sec/3600)),
      lon = ifelse(grepl("E", lon.sec.dir), 
                        as.numeric(lon.deg) + as.numeric(lon.min)/60 + lon.sec/3600,
                        -1 * (as.numeric(lon.deg) + as.numeric(lon.min)/60 + lon.sec/3600)),
    )
  
  # convert to sf object
  airports <- st_as_sf(airports, 
                            coords = c("lon", "lat"), crs = st_crs(centroids))
  airports$CWS.ind <- airports$State %in% unique(CWS.counties$state)
  airports$ucmr.ind <- airports$State %in% unique(ucmr.counties$state)
  
  # remove airports outside of 48 states + HI, AK
  outside50 <- c("'PPG", "'Z08", "'FAQ", "'MDY", "'STX", "'STT", "'PSE", 
                 "'SJU", "'BQN")
  
  airports <- airports %>% filter(!(LocationID %in% outside50))
  
    # now with LMOP data
  landfills.lmop <- landfills.lmop %>% 
    select(Landfill.ID, Landfill.Name, 
           lon = Longitude,
           lat = Latitude) %>% 
    filter(!is.na(lat) & !is.na(lon)) %>%
    # drop missing coords
    st_as_sf(coords = c("lon", "lat"), crs = st_crs(centroids))
  
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# clean up centroids
centroids.nosf <- centroids %>%
  st_coordinates() %>%
   cbind(st_drop_geometry(centroids),.)

centroids.nosf <- centroids.nosf %>%
  group_by(PWSID) %>%
  mutate(X = mean(X),
         Y = mean(Y))

# centroids.nosf <- st_as_sf(centroids.nosf, 
```


```{r, echo=FALSE, include=FALSE}
# demographic centering (by state)
CWS.counties <- CWS.counties %>%
  group_by(state) %>%
  mutate(mean.Hisp = mean(percHisp),
         mean.Black = mean(percBlack),
         mean.White = mean(percWhite),
         mean.poverty = mean(poverty)
         ) %>% ungroup()

CWS.counties <- CWS.counties %>%
  mutate(center.Hisp = percHisp - mean.Hisp,
         center.Black = percBlack - mean.Black,
         center.White = percWhite - mean.White,
         center.poverty = poverty - mean.poverty
         ) %>% ungroup()

ucmr.counties <- ucmr.counties %>%
  group_by(state) %>%
  mutate(mean.Hisp = mean(percHisp),
         mean.Black = mean(percBlack),
         mean.White = mean(percWhite),
         mean.poverty = mean(poverty)
         ) %>% ungroup()

ucmr.counties <- ucmr.counties %>%
  mutate(center.Hisp = percHisp - mean.Hisp,
         center.Black = percBlack - mean.Black,
         center.White = percWhite - mean.White,
         center.poverty = poverty - mean.poverty
         ) %>% ungroup()


```



# Interactive maps
## Statewide sampling data
Click on the panel in the bottom right to change layers.

```{r, echo=FALSE, warning=FALSE}

# function for making palettes
makepalette.f <- function(variable){

  variable_palette <- colorNumeric(palette = "Blues", CWS.counties$variable)
  
  variable_palette(variable)
}

# function for popups
popup.f <- function(dataset) {
  
  paste("<B>Demographics</B>", "<br/>",
        "% Hispanic: ", 
        round(dataset$percHisp, 0), "%", "<br/>",
        "% Black non-Hispanic: ",
        round(dataset$percBlack, 0), "%", "<br/>",
        "% White: ",
        round(dataset$percWhite, 0), "%", "<br/>",
        "% living under the federal poverty line: ",
        round(dataset$poverty, 0), "%", "<br/>", "<br/>",
        "<B>PFAS data (% systems with levels > 5 ng/L) </B>", "<br/>",
        "PFOA: ", 
        round(dataset$PFOA.avg, 0), "%", "<br/>",
        "PFOS: ", 
        round(dataset$PFOS.avg, 0), "%", "<br/>",
        "PFNA: ", 
        round(dataset$PFNA.avg, 0), "%", "<br/>",
        "PFHxS: ", 
        round(dataset$PFHxS.avg, 0), "%", "<br/>",
        "PFBS: ", 
        round(dataset$PFBS.avg, 0), "%", "<br/>",
        "At least 1 PFAS: ", 
        round(dataset$Any.avg, 0), "%", "<br/>",
        "Number of community water systems in dataset: ",
        dataset$num.CWS,
        sep = "")
}

limits <- st_bbox(ucmr.counties)

# prob best to define polygon function?

map1 <- leaflet(CWS.counties) %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB.Positron") %>%
  
  # other providers: https://leaflet-extras.github.io/leaflet-providers/preview/
  # PFAS variables
  addPolygons(fillColor = ~makepalette.f(PFOA.avg), stroke = TRUE, 
              color = "black", opacity = 1, weight = 1,
              fillOpacity = 1, group = "Detection of PFOA",
              highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                  fillOpacity = 0.9),
              label = CWS.counties$NAME,
              popup = popup.f(dataset = CWS.counties))  %>%
  addPolygons(fillColor = ~makepalette.f(PFOS.avg), stroke = TRUE, 
            color = "black", opacity = 1, weight = 1,
            fillOpacity = 1, group = "Detection of PFOS",
            highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                fillOpacity = 0.9),
            label = CWS.counties$NAME,
            popup = popup.f(dataset = CWS.counties)) %>%
  addPolygons(fillColor = ~makepalette.f(Any.avg), stroke = TRUE, 
          color = "black", opacity = 1, weight = 1,
          fillOpacity = 1, group = "Detection of ≥1 PFAS",
          highlightOptions = highlightOptions(fillColor = "darkblue", 
                                              fillOpacity = 0.9),
          label = CWS.counties$NAME,
          popup = popup.f(dataset = CWS.counties)) %>%

    addPolygons(fillColor = ~makepalette.f(percHisp), stroke = TRUE, 
                color = "black", opacity = 1, weight = 1,
                fillOpacity = 1, group = "% Hispanic residents",
                highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                    fillOpacity = 0.9),
                label = CWS.counties$NAME,
                popup = popup.f(dataset = CWS.counties)) %>%
  
    addPolygons(fillColor = ~makepalette.f(percBlack),
                stroke = TRUE, color = "black", opacity = 1, weight = 1,
                fillOpacity = 1, group = "% Black residents",
                highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                    fillOpacity = 0.9),
                label = CWS.counties$NAME,
                popup = popup.f(dataset = CWS.counties)) %>%
  
    addPolygons(fillColor = ~makepalette.f(percWhite),
              stroke = TRUE, color = "black", opacity = 1, weight = 1,
              fillOpacity = 1, group = "% White residents",
              highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                  fillOpacity = 0.9),
              label = CWS.counties$NAME,
              popup = popup.f(dataset = CWS.counties)) %>%
    addPolygons(fillColor = ~makepalette.f(center.Hisp), stroke = TRUE,
        color = "black", opacity = 1, weight = 1,
        fillOpacity = 1, group = "% Hispanic residents (centered)",
        highlightOptions = highlightOptions(fillColor = "darkblue",
                                            fillOpacity = 0.9),
        label = CWS.counties$NAME,
        popup = popup.f(dataset = CWS.counties)) %>%
    addPolygons(fillColor = ~makepalette.f(poverty),
              stroke = TRUE, color = "black", opacity = 1, weight = 1,
              fillOpacity = 1, group =  "% residents living under federal poverty line",
              highlightOptions = highlightOptions(fillColor = "darkblue", 
                                                  fillOpacity = 0.9),
              label = CWS.counties$NAME,
              popup = popup.f(dataset = CWS.counties)) %>%
  
    # PFAS sources
  addCircleMarkers(data = epa, radius = 3, group = "EPA Stewardship sites",
                   weight = 3,
                   color = "black", fillColor = "goldenrod", fillOpacity = 1) %>%
  addCircleMarkers(data = military, radius = 3, group = "Military fire-training areas",
                 weight = 3,
                 color = "black", fillColor = "red", fillOpacity = 1) %>%
  addCircleMarkers(data = airports, radius = 3, group = "Airports (AFFF certified)",
                 weight = 3, 
                 color = "black", fillColor = "green", fillOpacity = 1) %>%
  # addCircleMarkers(data = landfills.lmop, radius = 3, group = "Municipal landfills",
  #                weight = 3,
  #                color = "black", fillColor = "black", fillOpacity = 1) %>%
  addLayersControl(
    position = "bottomright",
    baseGroups  = c("% Hispanic residents", "% Hispanic residents (centered)",
                    "% Black residents", "% White residents",
                    "% residents living under federal poverty line",
                    "Detection of PFOA", "Detection of PFOS", "Detection of ≥1 PFAS"),
    overlayGroups = c("EPA Stewardship sites", "Military fire-training areas",
                      "Airports (AFFF certified)"),
    options = layersControlOptions(collapsed = TRUE)) %>%
    setMaxBounds(lng1 = as.numeric(limits[1]),
               lat1 = as.numeric(limits[2]) - 10,
               lng2 = as.numeric(limits[3]) + 10,
               lat2 = as.numeric(limits[4]) + 10
               )

setView(map1 %>% hideGroup(c("EPA Stewardship sites", "Military fire-training areas",
                     "Airports (AFFF certified)")),
        lat = 40, lng = 42, zoom = 3)


```


```{r, echo=FALSE, warning=FALSE}


```



```{r, echo=FALSE, eval=FALSE}
PFASsource_map2 <- PFAS_map1 %>%
  addMarkers(lng = suspected.NJ$Longitude,
             lat = suspected.NJ$Latitude, 
             icon = list(
                    iconUrl = 'suspected.png',
                    iconSize = c(20, 20)
                   ),
             popup = paste(suspected.NJ$FACIL_NAME, 
                           suspected.NJ$BRANCH, sep = ": ")) %>%
   addMarkers(lng = military.NJ$Longitude,
              lat = military.NJ$Latitude,
              icon = list(
                     iconUrl = 'military.jfif',
                     iconSize = c(20, 20)),
              popup = paste("ID", military.NJ$EWG_ID, sep = ": ")) %>%
   addMarkers(lng = epa.NJ$Longitude,
              lat = epa.NJ$Latitude,
              icon = list(
                     iconUrl = 'factory.png',
                     iconSize = c(20, 20)),
              popup = paste("Located in ", epa.NJ$City, ", NJ", sep = ""))

PFASsource_map2
```

## UCMR 3